// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU993BKajMNgoPDSvnzM6_yZWm0Gvwf8I',
    appId: '1:673555002485:web:0355793909e256c795b43c',
    messagingSenderId: '673555002485',
    projectId: 'safaipay-d1e25',
    authDomain: 'safaipay-d1e25.firebaseapp.com',
    storageBucket: 'safaipay-d1e25.firebasestorage.app',
    measurementId: 'G-P8WWY9BT8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbD4VV55Bxj9mJLhdWUrH4rYJwBLhE_w',
    appId: '1:673555002485:android:d9585f05bba67d5c95b43c',
    messagingSenderId: '673555002485',
    projectId: 'safaipay-d1e25',
    storageBucket: 'safaipay-d1e25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcr0dNEig5D-NeslwdWVP-26gwpZZkyP0',
    appId: '1:673555002485:ios:2d567c8fd591cd8f95b43c',
    messagingSenderId: '673555002485',
    projectId: 'safaipay-d1e25',
    storageBucket: 'safaipay-d1e25.firebasestorage.app',
    iosBundleId: 'com.example.garbageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcr0dNEig5D-NeslwdWVP-26gwpZZkyP0',
    appId: '1:673555002485:ios:2d567c8fd591cd8f95b43c',
    messagingSenderId: '673555002485',
    projectId: 'safaipay-d1e25',
    storageBucket: 'safaipay-d1e25.firebasestorage.app',
    iosBundleId: 'com.example.garbageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU993BKajMNgoPDSvnzM6_yZWm0Gvwf8I',
    appId: '1:673555002485:web:3e7f81e84011fb5595b43c',
    messagingSenderId: '673555002485',
    projectId: 'safaipay-d1e25',
    authDomain: 'safaipay-d1e25.firebaseapp.com',
    storageBucket: 'safaipay-d1e25.firebasestorage.app',
    measurementId: 'G-W2MY6ZKZ6W',
  );
}
